### ISSUE TITLE
Fehler in der PartyEntity

### ISSUE THREAD

**Issue by Sparkobbable** [SpotifyVotingQueue/svq-backend#9]
```
2022-12-16T09:09:50.586706+00:00 app[web.1]: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: de.spotifyvotingqueue.svqbackend.database.model.PartyEntity.queueTracks, could not initialize proxy - no Session
2022-12-16T09:09:50.586706+00:00 app[web.1]: 	at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:614) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
2022-12-16T09:09:50.586707+00:00 app[web.1]: 	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:218) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
2022-12-16T09:09:50.586707+00:00 app[web.1]: 	at org.hibernate.collection.internal.AbstractPersistentCollection.readSize(AbstractPersistentCollection.java:162) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
2022-12-16T09:09:50.586708+00:00 app[web.1]: 	at org.hibernate.collection.internal.PersistentBag.isEmpty(PersistentBag.java:376) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
2022-12-16T09:09:50.586708+00:00 app[web.1]: 	at de.spotifyvotingqueue.svqbackend.services.QueueService.syncRemoteQueue(QueueService.kt:58) ~[classes!/:na]
2022-12-16T09:09:50.586708+00:00 app[web.1]: 	at de.spotifyvotingqueue.svqbackend.services.QueueService.syncRemoteQueueForAllParties(QueueService.kt:51) ~[classes!/:na]
2022-12-16T09:09:50.586709+00:00 app[web.1]: 	at jdk.internal.reflect.GeneratedMethodAccessor90.invoke(Unknown Source) ~[na:na]
2022-12-16T09:09:50.586709+00:00 app[web.1]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
2022-12-16T09:09:50.586710+00:00 app[web.1]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
2022-12-16T09:09:50.586711+00:00 app[web.1]: 	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.3.22.jar!/:5.3.22]
2022-12-16T09:09:50.586711+00:00 app[web.1]: 	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.22.jar!/:5.3.22]
2022-12-16T09:09:50.586712+00:00 app[web.1]: 	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95) ~[spring-context-5.3.22.jar!/:5.3.22]
2022-12-16T09:09:50.586712+00:00 app[web.1]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
2022-12-16T09:09:50.586713+00:00 app[web.1]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
2022-12-16T09:09:50.586713+00:00 app[web.1]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
2022-12-16T09:09:50.586713+00:00 app[web.1]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
2022-12-16T09:09:50.586714+00:00 app[web.1]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
2022-12-16T09:09:50.586714+00:00 app[web.1]: 	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
2022-12-16T09:09:50.586715+00:00 app[web.1]: 
```

**Comment by Sparkobbable** [comment]
@jpfrehe verstehst du den Fehler? Hängt irgendwie mit der syncRemoteQueue, bzw. dem JPA Model darin zusammen

**Comment by jpfrehe** [comment]
Da fällt uns auf die füße, dass die queue noch nicht ganz so schick geregelt ist. Schau ich mir an
